config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tops#index"

  resources :users, only: [:new, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member, as: :followings
    get :followers, on: :member, as: :followers
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy, :update]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'ranking'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :tag_names
  require 'aws-sdk-rekognition'


  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts

  validates :image, presence: true

  def liked?(user)
    likes.where(user_id: user.id).exists?
  end

  def save_tags(tags)
    tags.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      self.tags << tag
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    []
  end

  def self.ransackable_associations(auth_object = nil)
    ['user', 'tags']
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_posts, dependent: :destroy
  has_many :posts, through: :tag_posts


  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, UserAvatarUploader
  authenticates_with_sorcery!
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: { maximum: 20, allow_blank: true }
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, confirmation: true, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id)&.destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def own?(object)
    id == object.id
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_authenticated
    redirect_to new_user_session_path, alert: "Please login first"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      flash[:notice] = "コメントしました"
      redirect_to post_path(comment.post)
    else
      flash[:alert] = "コメントに失敗しました"
      redirect_to post_path(comment.post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_to post_path(params[:post_id])
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]
  before_action :require_login, only: %i[show edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:user, :tags).order(created_at: :desc).page(params[:page]).per(9)
  end

  def ranking
    @ranked_posts = Post.includes(:user, :tags).left_joins(:likes).group(:id).order('COUNT(likes.id) DESC').page(params[:page]).per(9)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:tag_names].split(',')
  
    if @post.save
      @post.save_tags(tag_list)
      ImageRecognitionJob.perform_later(@post.id)
      redirect_to posts_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end
  
  def edit; end

  def update
    if @post.update(post_params)
      tag_list = params[:post][:tag_names].split(',')
      @post.save_tags(tag_list)
      redirect_to posts_path, success: '更新しました'
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to user_path(@post.user), success: '削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:image, :description, :tag_names)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy followings followers]
  # User registration
  def new
    @user = User.new
  end

  def show
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(9)
  end

  def edit;end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Successfully updated user."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    # If the user is saved successfully than respond with json data format.
    if @user.save
      flash[:notice] = "Successfully created user."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :profile)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<footer class="flex justify-between items-center mb-2">
    <div class="flex items-center">
        <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white">
          <%= image_tag comment.user.avatar.thumb.url, class: 'mr-2 w-6 h-6 rounded-full' %><%= comment.user.name %>
        </p>
    </div>
</footer>
<p class="text-gray-500 dark:text-gray-400"><%= comment.body %></p>

app/views/comments/_comments.html.erb
<article class="p-6 mb-6 text-base bg-white rounded-lg dark:bg-gray-900">
  <%= render @comments %>
</article>

app/views/comments/_form.html.erb
<div class="flex justify-between items-center mb-6">
<h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">コメント (<%= post.comments.count %>)</h2>
</div>
<%= form_with model: [post, comment], local: true, html: { class: "mb-6" } do |f| %>
  <div class="py-2 px-4 mb-4 bg-white rounded-lg rounded-t-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
    <%= f.label :body, id: "comment", class: "sr-only" do %>Your comment<% end %>
    <%= f.text_area :body, placeholder: "コメントを入力してください", rows: "4", id: "comment", class: "px-0 w-full text-sm border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800" %>
  </div>
  <%= f.submit '投稿', class: 'inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-indigo-500 bg-indigo-100 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
<% end %>

app/views/posts/_like.html.erb
<%= link_to post_likes_path(@post.id), method: :post do %>
  <i class="far fa-heart"></i>
<% end %>

app/views/posts/_like_button.html.erb
<% if post.liked?(post.user) %>
  <%= render 'posts/unlike', post: post %>
<% else %>
  <%= render 'posts/like', post: post %>
<% end %>

app/views/posts/_unlike.html.erb
<%= link_to post_like_path(@post.id), method: :delete do %>
  <i class="fas fa-heart"></i>
<% end %>

app/views/posts/index.html.erb
<section class="py-5 text-center container">
  <div>
    <%= render 'shared/search' %>
  </div>
</section>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-15 mx-auto">
    <div class="flex flex-wrap -m-4">
      <% @posts.each do |post| %>
        <div class="p-4 md:w-1/3">
          <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
            <%= image_tag post.image.url, class: "lg:h-48 md:h-36 w-full object-cover object-center", alt: "Post image" %>
            <div class="p-6">
              <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"><%= post.user.name %></h2>
              <div class="flex space-x-2">
              <% post.tags.each do |tag| %>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3">#<%= tag.name %></h1>
              <% end %>
              </div>
              <p class="leading-relaxed mb-3"><%= post.description %></p>
              <div class="flex items-center flex-wrap ">
                <button type="button" class="text-green-500 inline-flex items-center md:mb-2 lg:mb-0">
                  <%= link_to 'Learn More', post_path(post) %>
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
                </button>
                <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                  <div class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <i class="far fa-heart"></i>
                  </div><%= post.likes.count %>
                </span>
                <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                  <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                  </svg><%= post.comments.count %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="m-4">
    <%= paginate @posts %>
    </div >
  </div>
</section>

app/views/posts/new.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class=" text-center text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                  投稿作成
              </h1>
                <%= form_with model: @post, local: true, html: {class: "row g-3 needs-validation space-y-4 md:space-y-4" }  do |f| %>
                  <div>
                      <%= f.label :image, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
                      <%= f.file_field :image, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
                  </div>
                  <div>
                     <%= f.label :description, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
                     <%= f.text_area :description, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
                  </div>
                  <div>
                    <%= f.label :tag_names, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
                    <%= f.text_field :tag_names, placeholder: ',で区切ると複数登録できます', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
                  </div>
                  <div>
                  <%= f.submit "投稿する", class: 'w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
                  </div>
                <% end %>
          </div>
      </div>
  </div>
</section>

app/views/posts/ranking.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-15 pt-12 mx-auto">
    <div class="flex flex-wrap -m-4">
      <% @ranked_posts.each do |post| %>
        <div class="p-4 md:w-1/3">
          <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
            <%= image_tag post.image.url, class: "lg:h-48 md:h-36 w-full object-cover object-center", alt: "Post image" %>
            <div class="p-6">
              <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"><%= post.user.name %></h2>
              <div class="flex space-x-2">
              <% post.tags.each do |tag| %>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3">#<%= tag.name %></h1>
              <% end %>
              </div>
              <p class="leading-relaxed mb-3"><%= post.description %></p>
              <div class="flex items-center flex-wrap ">
                <button type="button" class="text-green-500 inline-flex items-center md:mb-2 lg:mb-0">
                  <%= link_to 'Learn More', post_path(post) %>
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
                </button>
                <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                  <div class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <i class="far fa-heart"></i>
                  </div><%= post.likes.count %>
                </span>
                <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                  <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                  </svg><%= post.comments.count %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="m-4">
    <%= paginate @ranked_posts %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-col px-5 py-24 justify-center items-center">
    <%= image_tag @post.image.url, class: "lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" %>
    <div class="w-full md:w-2/3 flex flex-col mb-16 items-center text-center">
    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1"><%= link_to @post.user.name, user_path(@post.user) %></h1>
    <% if current_user.id != @post.user_id %>
    <div class="flex mb-4">
      <span class="flex items-center">
        <%= render 'users/follow_button', user: @user %>
      </span>
      <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
        <div class="text-gray-500">
        <%= render 'posts/like_button', class: "w-5 h-5", post: @post %>
        </div>
      </span>
    </div>
    <% end %>
    <% @post.tags.each do |tag| %>
    <h2 class="text-sm title-font text-gray-500 tracking-widest">#<%= tag.name %></h2>
    <% end %>
    <p class="leading-relaxed"><%= @post.description %></p>
  </div>
</section>
<section class="bg-white dark:bg-gray-900 py-8 lg:py-16">
 <div class="max-w-2xl mx-auto px-4">
  <%= render 'comments/form', { post: @post, comment: @comment } %>
  <%= render 'comments/comments', { comments: @comments } %>
 </div>
</section>

app/views/posts/test.erb
<%= form_with model: @user, local: true, html: {class: "row g-3 needs-validation" }  do |f| %>
  <div class="col-12 d-flex justify-content-center">
  <%= image_tag @user.avatar.thumb.url,
                class: 'rounded-circle',
                size: '100x100' %>
  </div>

  <div class="col-12">
    <%= f.label :avatar, class: 'form-label' %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>

  <div class="col-12">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="col-12">
    <%= f.label :profile, class: 'form-label' %>
    <%= f.text_area :profile, class: 'form-control' %>
  </div>

  <div class="col-12">
    <%= f.submit "プロフィールを編集する", class: 'btn btn-primary w-100' %>
  </div>
  <div class="col-12">
  </div>
<% end %>

app/views/relationships/followers.html.erb
<h1>Relationships#followers</h1>
<p>Find me in app/views/relationships/followers.html.erb</p>

app/views/relationships/followings.html.erb
<h1>Relationships#followings</h1>
<p>Find me in app/views/relationships/followings.html.erb</p>

app/views/users/_follow_button.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: 'py-1 px-4 inline-flex justify-center items-center gap-2 rounded-full border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800' %>
<% else %>
  <%= link_to "フォロー", user_relationships_path(user.id), method: :post, class: 'py-1 px-4 inline-flex justify-center items-center gap-2 rounded-full border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800' %>
<% end %>

app/views/users/show.html.erb
<div class="max-w-2xl sm:max-w-sm md:max-w-sm lg:max-w-sm xl:max-w-sm sm:mx-auto md:mx-auto lg:mx-auto xl:mx-auto mt-16 rounded-lg text-gray-900">
    <div class="mx-auto w-32 h-32 relative -mt-10 border-4 border-white rounded-full overflow-hidden">
        <%= image_tag @user.avatar.thumb.url, class: "object-cover object-center h-32" %>
    </div>
    <div class="text-center mt-2">
        <h2 class="font-semibold"><%= @user.name %></h2>
        <p class="text-gray-500"><%= @user.profile %></p>
    </div>
    <ul class="py-4 mt-2 text-gray-700 flex items-center justify-around">
        <li class="flex flex-col items-center justify-around">
          <%= link_to followings_user_path(@user) do %>
            <svg class="w-4 fill-current text-blue-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
              <span>フォロー中</span>
            </svg>
          <% end %>
            <div><%= @user.followings.count %></div>
        </li>
        <li class="flex flex-col items-center justify-around">
          <%= link_to followers_user_path(@user) do %>
            <svg class="w-4 fill-current text-blue-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
              <span>フォロワー</span>
            </svg>
          <% end %>
            <div><%= @user.followers.count %></div>
        </li>
    </ul>
    <div class="p-4 border-t mx-8 mt-2 text-center">
     <% if @user == current_user %>
      <%= link_to "編集", edit_user_path(@user), class: 'w-1/2 block mx-auto rounded-full bg-gray-600 hover:shadow-lg font-semibold text-white px-6 py-2' %>
     <% else %>
      <%= render 'users/follow_button', user: @user %>
    <% end %>
    </div>
</div>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-15 mx-auto">
    <div class="flex flex-wrap -m-4">
      <% @posts.each do |post| %>
        <div class="p-4 md:w-1/3">
          <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
            <%= image_tag post.image.url, class: "lg:h-48 md:h-36 w-full object-cover object-center", alt: "Post image" %>
            <div class="p-6">
              <% if @user == current_user %>
              <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, post_path(post), method: :delete, data: { confirm: '投稿を削除しますか？' } %>
              <% end %>
              <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"><%= post.user.name %></h2>
              <div class="flex space-x-2">
              <% post.tags.each do |tag| %>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3">#<%= tag.name %></h1>
              <% end %>
              </div>
              <p class="leading-relaxed mb-3"><%= post.description %></p>
              <div class="flex items-center flex-wrap ">
                <button type="button" class="text-green-500 inline-flex items-center md:mb-2 lg:mb-0">
                  <%= link_to 'Learn More', post_path(post) %>
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
                </button>
                <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                  <div class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <i class="far fa-heart"></i>
                  </div><%= post.likes.count %>
                </span>
                <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                  <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                  </svg><%= post.comments.count %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="m-4">
    <%= paginate @posts %>
    </div>
  </div>
</section>