config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tops#index"

  resources :users, only: [:new, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member, as: :followings
    get :followers, on: :member, as: :followers
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy, :update]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'ranking'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :tag_names
  require 'aws-sdk-rekognition'


  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts

  validates :image, presence: true

  def liked?(user)
    likes.where(user_id: user.id).exists?
  end

  def save_tags(tags)
    tags.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      self.tags << tag
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    []
  end

  def self.ransackable_associations(auth_object = nil)
    ['user', 'tags']
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_posts, dependent: :destroy
  has_many :posts, through: :tag_posts


  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, UserAvatarUploader
  authenticates_with_sorcery!
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: { maximum: 20, allow_blank: true }
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, confirmation: true, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id)&.destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def own?(object)
    id == object.id
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      flash[:notice] = "コメントしました"
      redirect_to post_path(comment.post)
    else
      flash[:alert] = "コメントに失敗しました"
      redirect_to post_path(comment.post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_to post_path(params[:post_id])
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]
  before_action :require_login, only: %i[show edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:user, :tags).order(created_at: :desc).page(params[:page]).per(9)
  end

  def ranking
    @ranked_posts = Post.includes(:user, :tags).left_joins(:likes).group(:id).order('COUNT(likes.id) DESC').page(params[:page]).per(9)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:tag_names].split(',')
  
    if @post.save
      @post.save_tags(tag_list)
      ImageRecognitionJob.perform_later(@post.id)
      redirect_to posts_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end
  
  def edit; end

  def update
    if @post.update(post_params)
      tag_list = params[:post][:tag_names].split(',')
      @post.save_tags(tag_list)
      redirect_to posts_path, success: '更新しました'
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to user_path(@post.user), success: '削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:image, :description, :tag_names)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  
  def index; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to posts_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy followings followers]
  # User registration
  def new
    @user = User.new
  end

  def show
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(9)
  end

  def edit;end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Successfully updated user."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    # If the user is saved successfully than respond with json data format.
    if @user.save
      flash[:notice] = "Successfully created user."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :profile)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_sessions/new.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class=" text-center text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                  ログイン
              </h1>
                <%= form_with url: user_sessions_path, method: :post, local: true, html: {class: "row g-3 needs-validation space-y-4 md:space-y-4" }  do |f| %>
                  <div>
                      <%= f.label :email, User.human_attribute_name(:email), class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
                      <%= f.email_field :email, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
                  </div>
                  <div>
                     <%= f.label :password, User.human_attribute_name(:password), class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
                     <%= f.password_field :password, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
                  </div>
                  <div>
                  <%= f.submit "ログイン", class: 'w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
                  </div>
                  <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                      アカウントをお持ちでない場合 <%= link_to 'Sign up', new_user_path, class: 'font-medium text-primary-600 hover:underline dark:text-primary-500' %>
                  </p>
                <% end %>
          </div>
      </div>
  </div>
</section>